import os
import json
import logging
from pydantic import BaseModel, Field
from openai import OpenAI


logger = logging.getLogger(__name__)



# ----------------------------------------------------
# STRUCTURED AI OUTPUT SCHEMAS
# ----------------------------------------------------
class ProspectQualification(BaseModel):
    """Structured response schema generated by the AI Research Agent."""
    qualification_status: str = Field(
        description="Must be exactly one of: 'qualified', 'unqualified', or 'review_required'"
    )
    qualification_reason: str = Field(
        description="Clear 1-2 sentence explanation pinpointing why they matched or failed campaign guidelines."
    )
    score: int = Field(
        description="An ICP alignment score scale from 0 (completely irrelevant) to 100 (perfect match)."
    )


# ----------------------------------------------------
# THE AI RESEARCH AGENT ENGINE
# ----------------------------------------------------
def ai_research_agent(campaign: dict, raw_scraped_data: dict) -> ProspectQualification:
    """
    Evaluates raw prospect data against strict user campaign goals 
    using OpenAI's natively strict JSON structured outputs mode.
    """
    system_prompt = f"""
    You are an elite B2B Sales Intel & Lead Qualification Agent.
    Your mission is to strictly verify if a target prospect fits the current GTM Campaign framework.
    
    --- CAMPAIGN BOUNDARIES ---
    Ideal Customer Profile (ICP): {campaign.get('icp')}
    Target Geographies: {', '.join(campaign.get('geography', []))}
    Target Roles/Personas: {', '.join(campaign.get('target_personas', []))}
    Core Campaign Objective: {campaign.get('objective')}
    Agent Working Instructions: {campaign.get('agent_instructions')}
    Hard Qualification Checklist: {', '.join(campaign.get('qualification_criteria', []))}
    
    --- BACKGROUND KNOWLEDGE CONTEXT ---
    {campaign.get('campaign_specific_knowledge', 'No custom text documentation provided.')}
    """

    user_prompt = f"""
    Analyze and parse this incoming raw scraped payload:
    {json.dumps(raw_scraped_data, indent=2)}
    
    Return your categorization decision clearly mapped to the required target JSON schemas.
    """

    try:
        completion = openai_client.beta.chat.completions.parse(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            response_format=ProspectQualification,
        )
        return completion.choices.message.parsed
        
    except Exception as e:
        logger.error(f"AI Agent inference or structured validation failed: {e}")
        return ProspectQualification(
            qualification_status="review_required",
            qualification_reason=f"Pipeline Error: Failed to execute AI qualification model cleanly. {str(e)}",
            score=50
        )


# ----------------------------------------------------
# BACKGROUND ORCHESTRATOR PIPELINE
# ----------------------------------------------------
def run_research_pipeline(campaign_data: dict):
    """
    Asynchronous background runner handling scraping emulation,
    AI verification processing steps, and clean bulk writes to the prospects table.
    """
    logger.info(f"🌀 Processing pipeline execution sequence for Campaign: {campaign_data['id']}")
    
    # Mocking real-world scraped data incoming loop (Replace this block with your actual scraping integration)
    mock_scraped_leads = [
        {
            "first_name": "Arjun",
            "last_name": "Sharma",
            "email": "arjun@vortexai.dev",
            "linkedin_url": "https://linkedin.com",
            "job_title": "Founder & CEO",
            "company_name": "Vortex AI Solutions",
            "company_website": "https://vortexai.dev",
            "location": "Bengaluru, India",
            "employee_count": 14,
            "industry": "Artificial Intelligence / Enterprise Software"
        },
        {
            "first_name": "Marcus",
            "last_name": "Vance",
            "email": "marcus.v@globalshippingcorp.com",
            "linkedin_url": "https://linkedin.com",
            "job_title": "Operations Lead",
            "company_name": "Global Shipping Corp",
            "company_website": "https://globalshippingcorp.com",
            "location": "Texas, US",
            "employee_count": 1250,
            "industry": "Logistics & Supply Chain"
        }
    ]
    
    final_database_payload = []

    for raw_lead in mock_scraped_leads:
        ai_decision = ai_research_agent(campaign_data, raw_lead)
        
        prospect_row = {
            "campaign_id": campaign_data["id"],
            "profile_id": campaign_data["profile_id"],
            "first_name": raw_lead.get("first_name"),
            "last_name": raw_lead.get("last_name"),
            "email": raw_lead.get("email"),
            "linkedin_url": raw_lead.get("linkedin_url"),
            "job_title": raw_lead.get("job_title"),
            "company_name": raw_lead.get("company_name"),
            "company_website": raw_lead.get("company_website"),
            "location": raw_lead.get("location"),
            "qualification_status": ai_decision.qualification_status,
            "qualification_reason": ai_decision.qualification_reason,
            "raw_enrichment_data": {
                **raw_lead,
                "ai_fit_score": ai_decision.score
            }
        }
        final_database_payload.append(prospect_row)

    if final_database_payload:
        try:
            response = supabase.table("prospects").insert(final_database_payload).execute()
            logger.info(f"✅ Successfully wrote {len(response.data)} fresh prospect profiles to Supabase.")
        except Exception as db_err:
            logger.error(f"❌ Transaction processing failure inside Supabase Write lifecycle: {db_err}")
